const randomAnime =

[
    {title: "Fairy Tail"},
    {title: "Bleach"},
    {title: "Mobile Suit Gundam 00"},
    {title: "Mobile Suit Gundam: Iron Blooded Orphans"},
    {title: "Mobile Suit Gundam Unicorn"},
    {title: "Outlaw Star"},
    {title: "Princess Mononoke"},
    {title: "Spirited Away"},
    {title: "Nausicaä of the Valley of the Wind"},
    {title: "Howl's Moving Castle"},
    {title: "Full Metal Alchemist: Brotherhood"},
    {title: "Kill La Kill"},
    {title: "Inuyasha"},
    {title: "Gurren Lagann"},
    {title: "Code Geass: Lelouch of the Rebellion"},
    {title: "Code Geass: Akito the Exile"},
    {title: "Akira"},
    {title: "Ghost in the Shell"},
    {title: "One Punch Man"},
    {title: "The Seven Deadly Sins"},
    {title: "God Eater"},
    {title: "Darling in the Franxx"},
    {title: "Dragon Ball Z"},
    {title: "Dragon Ball GT"},
    {title: "Dragon Ball Super"},
    {title: "Rokka: Braves of the Six Flowers"},
    {title: "Strain: Strategic Armored Infantry"},
    {title: "Break Blade"},
    {title: "Dr. Stone"},
    {title: "Fire Force"},
    {title: "My Hero Academia"},
    {title: "Sword of the Stranger"},
    {title: "Naruto"},
    {title: "Naruto: Shippuden"},
    {title: "Boruto: Naruto Next Generations"},
    {title: "Attak on Titan"},
    {title: "Claymore"},
    {title: "Soul Eater"},
    {title: "Escaflowne"},
    {title: "Voltron"},
    {title: "Neon Genesis Evangelion"},
    {title: "Demon Slayer: Kimetsu no Yaiba"},
    {title: "Kabaneri of the Iron Fortress"},
    {title: "King of Thorn"},
    {title: "Blue Exorcist"},
    {title: "Noragami"},
    {title: "Cells at Work"},
    {title: "Is It Wrong to Try to Pick Up Girls in a Dungeon?"},
    {title: "How NOT to Summon a Demon Lord"},
    {title: "Avatar: The Last Airbender"},
    {title: "Avatar: The Legend of Korra"},
    {title: "Yu Yu Hakusho"},
    {title: "Guyver"},
    {title: "Aldnoah Zero"},
    {title: "Knight's & Magic"},
    {title: "Terra Formars"},
    {title: "Black Blood Brothers"},
    {title: "Space Pirate Captain Harlock"},
    {title: "Tsubasa: Reservoir Chronicle"},
    {title: "Origin: Spirits of the Past"},
    {title: "Mary and the Witch's Flower"},
    {title: "Space Battleship Yamato"},
    {title: "Seraph of the End"},
    {title: "Fate: Stay Night"},
    {title: "Fate/Zero"},
    {title: "The Rising of the Shield Hero"}
]

export default randomAnime;